plugin:
    antislime:
        enabled: true
    timezone:
        enabled: true
    togglemode:
        enabled: false
    mentortp:
        enabled: true
    endernerf:
        enabled: true
    pigjoust:
        enabled: true
    hatme:
        enabled: true
#hatme config
        enable: true
        allowed: 
        - 1
        - 2
        - 3
        - 4
        - 5
        - 12
        - 13
        - 14
        - 15
        - 17
        - 18
        - 20
        - 22
        - 23
        - 24
        - 25
        - 35
        - 41
        - 42
        - 44
        - 45
        - 46
        - 47
        - 48
        - 49
        - 52
        - 54
        - 57
        - 58
        - 80
        - 81
        - 82
        - 87
        - 88
        - 89
        - 91
        - 98
        - 103
        - 112
        opnorestrict: true
        notAllowedMsg: Invalid Item
        hatversion: 9.6-ECV
    mobcontrol:
        enabled: true
        worlds: [testworld]
        mobs: [Snowman]
    lockdown:
        enabled: true
        noticifationmsg: "!!!SERVER IS IN LOCKDOWN-MODE!!!"
        rejectmsg: "Server Full"
    who:
        enabled: true
    blockalert:
        enabled: true
        notifyOnCanceledBreak: false
        notifyOnCanceledPlace: true
        worlds:
            break:
                survival: 
# Goldblock
                    - 41
# Diamondblock
                    - 57
            place:
                survival:
# Bedrock
                    - 7
# TNT
                    - 46
    afkbooter:
        enabled: true
        version: ""
        debug: false
        kick-timeout: 600
        timeout-check-interval: 60
        player-count-threshold: 0
        kick-message: "Kicked for idling."
        kick-broadcast: "Kicked for idling."
        exempt-players: ""
        ignore-vehicle-movement: true
        event-player-move: false
        event-player-chat: true
        event-inventory-open: true
        event-player-command-preprocess: true
        event-player-drop-item: true
        event-block-place: true
        event-block-break: true
        event-player-interact: true
        event-player-interact-entity: true
    vanish:
        enabled: true
